- name: Criando o diretorio da app Giropops
  file: path={{ item }} state=directory mode='0755'
  with_items:
    - /opt/giropops
    - /opt/giropops/logs
    - /opt/giropops/conf
  register: criando_diretorios

- name: Copiando o arquivo de deployment da app para o host
  template:
    src: app-v1.yml.j2
    dest: /opt/giropops/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_template

- name: Copiando o arquivo de service da app para o host
  copy: src={{ item.src }} dest={{ item.dest }} mode='0755'
  with_items:
    - { src: 'service-app.yml', dest: '/opt/giropops/service-app.yml' }
  register: copiando_service_file

- name: Criando o deployment da App Giropops
  command: kubectl apply -f /opt/giropops/app-v1.yml
  register: deploy_app
  changed_when: '"app-v1 created" in deploy_app.stdout'

- name: Criando o Service da App Giropops
  command: kubectl apply -f /opt/giropops/service-app.yml
  register: deploy_svc_app
  changed_when: '"app-v1 created" in deploy_svc_app.stdout'

