- name: Download Script Instalacao Docker
  get_url:
    url: "{{ url_docker_script }}"
    dest: "{{ dst_docker_script }}"
    mode: '0755'  
  register: download_script

- name: Instalando o Docker
  command: "{{ dst_docker_script }}"
  when: download_script
  notify: Restart Docker
  register: instalando_docker

- name: Removendo script Instalacao Docker
  file:
    path: "{{ dst_docker_script }}"
    state: absent
  register: removendo_script

- name: Adicionando as chaves do repo apt do k8s
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adicionando o repo do k8s
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Instalando os pacotes kubeadm, kubelet e kubectl
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl
  notify: Restart Kubelet

