- name:
  debug:
    msg: "[WORKER] K8S_TOKEN_HOLDER - O token eh {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

- name:
  debug:
    msg: "[WORKER] K8S_TOKEN_HOLDER - O hash eh {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"

- name: Removendo o cluster
  command: 
    kubeadm reset --force
  register: kubeadm_reset

- name: Adicionando o worker ao cluster k8s
  command:
    kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }} 
    --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }} 
    {{K8S_MASTER_NODE_IP}}:{{K8S_API_SECURE_PORT}}
